#rock paper scissors!! 
'''
import random
options = ("rock", "paper", "scissors")
running = True


while running:   # we use variables instead of saying while true in bigger programmes... cuz it is easier to find when you click on the variable you can find it as our IDE highlights it
    player = None
    computer = random.choice(options)
    while player not in options:
        player = input("Choose your option (rock , paper , scissors): ")
       
    print(f"Player: {player}")
    print(f"Computer: {computer}")

    if player == computer:
        print("It's a tie!")
    elif player== "rock" and computer== "scissors":
        print("You win!")
    elif player== "paper" and computer== "rock":
        print("You win!")
    elif player== "scissors" and computer== "paper":
        print("You win!")
    else:
        print("You lose")
    
    if not input("Do you want to play again?(y/n): ")=="y":
        running= False

print("Thanks for playing!")
'''


import random
dice_art = {
    1: ("┌─────────┐",
        "│         │",
        "│    ●    │",
        "│         │",
        "└─────────┘"),
    2: ("┌─────────┐",
        "│  ●      │",
        "│         │",
        "│      ●  │",
        "└─────────┘"),
    3: ("┌─────────┐",
        "│  ●      │",
        "│    ●    │",
        "│      ●  │",
        "└─────────┘"),
    4: ("┌─────────┐",
        "│  ●   ●  │",
        "│         │",
        "│  ●   ●  │",
        "└─────────┘"),
    5: ("┌─────────┐",
        "│  ●   ●  │",
        "│    ●    │",
        "│  ●   ●  │",
        "└─────────┘"),
    6: ("┌─────────┐",
        "│  ●   ●  │",
        "│  ●   ●  │",
        "│  ●   ●  │",
        "└─────────┘")
}

dice = [] #making a list cuz we are gonna append things in it 
total = 0 #variable to coun
num_dice = int(input("Enter the number of dice: ")) #taking input for amount of die 

for number in range(num_dice):
    dice.append(random.randint(1,6))
print(dice)

#Horizontal printing of ASCII art 
for line in range(5): #as you have to print every line of the art - 
    for die in dice:  #goes through the created dice list 
        print(dice_art.get(die)[line], end="") 
        '''#accesses the dictionary - gets the first die from list(dice) - which is randomly generated by random module
            and prints the first line(element) of tupple , goes on doing this as the value of die increases
            i.e gets to the next value of dice list - once all the elements of dice lists have been iterated through
            
            increments the value of line - from 1 to 2 - then goes over the inner loop again in the similar fashion'''
    
    print() #to get into other line after each inner loop
    

for die in dice:
    total += die
print(total)

